# Numpy 

In [1]:
my_list= [1,2,3,4]

In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.87007751, 0.26995485, 0.54622103, 0.52244823, 0.94243911])

In [13]:
np.random.rand(5,5)

array([[0.03199701, 0.44892846, 0.79571889, 0.03000199, 0.92400609],
       [0.62071037, 0.37672578, 0.30137202, 0.14760808, 0.48453019],
       [0.93801507, 0.03262334, 0.36689448, 0.83297268, 0.82663047],
       [0.91029924, 0.08806249, 0.79154946, 0.8178366 , 0.81486288],
       [0.55757853, 0.10441801, 0.67415844, 0.90941777, 0.8715536 ]])

In [14]:
np.random.randn(4,4)

array([[-0.66457469,  1.18243046, -1.69154923, -0.79507836],
       [-0.4528738 ,  0.29529375,  1.2965459 ,  1.16470217],
       [ 0.35514391, -1.28379185, -1.43398324,  1.22504171],
       [ 0.78540668, -0.03872825,  0.94285198, -0.82124963]])

In [15]:
np.random.randint(0,100,4)

array([88, 36, 61, 10])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)

In [19]:
ranarr

array([44,  0, 11, 21,  5,  2, 31, 47, 29, 16])

In [20]:
arr=arr.reshape(5,5)

In [21]:
ranarr=ranarr.reshape(2,5)

In [22]:
ranarr.max()

47

In [23]:
ranarr.min()

0

In [24]:
ranarr.argmax()

7

In [25]:
arr.shape

(5, 5)

In [26]:
arr.dtype

dtype('int64')

## Indexing and Selection

In [28]:
arr = np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [31]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])